<script lang="ts">
	import {
		faHouse,
		faFileLines,
		faPeopleGroup,
		faCar,
		faCarSide,
		faGun,
		faFileSignature,
		faAddressBook,
		faGavel,
		faBook,
		faLock,
		faScaleBalanced,
		faUsersGear,
		faUserShield,
		faUserLock,
		faUserLarge,
		faIdBadge,
		faXmark,
		faMagnifyingGlass,
		faSort,
		faSortUp,
		faSortDown,
		faArrowsRotate,
		faChevronLeft,
		faChevronRight,
		faChevronDown,
		faCircleCheck,
		faCircleExclamation,
		faTriangleExclamation,
		faCopy,
		faCompress,
		faExpand,
		faPlus,
		faTrash,
		faPen,
		faLocationCrosshairs,
		faCarBattery,
		faVideo,
		faVideoSlash,
		faVolumeHigh,
		faShieldHalved,
		faHandcuffs,
		faBriefcaseMedical,
		faCircleUser,
		faPhone,
		faFlag,
		faCheck,
		faWalkieTalkie,
		faHelicopter,
		faMotorcycle,
		faCircleQuestion,
		faThumbtack,
		faLocationDot,
		faStopwatch,
		faLinkSlash,
		faCamera,
		faChevronUp,
		faCog,
		faShare,
		faTruckMedical,
		faTruckRampBox,
		faClipboardList,
		faHourglassHalf,
		faFire,
		type IconDefinition,
	} from '@fortawesome/free-solid-svg-icons';

	const ICONS: Record<string, IconDefinition> = {
		house: faHouse,
		'file-lines': faFileLines,
		people: faPeopleGroup,
		car: faCar,
		'car-side': faCarSide,
		gun: faGun,
		'file-signature': faFileSignature,
		'address-book': faAddressBook,
		gavel: faGavel,
		book: faBook,
		lock: faLock,
		'scale-balanced': faScaleBalanced,
		'users-gear': faUsersGear,
		'user-shield': faUserShield,
		'user-lock': faUserLock,
		'user-large': faUserLarge,
		'id-badge': faIdBadge,
		xmark: faXmark,
		'magnifying-glass': faMagnifyingGlass,
		sort: faSort,
		'sort-up': faSortUp,
		'sort-down': faSortDown,
		'arrows-rotate': faArrowsRotate,
		'chevron-left': faChevronLeft,
		'chevron-right': faChevronRight,
		'chevron-down': faChevronDown,
		'circle-check': faCircleCheck,
		'circle-exclamation': faCircleExclamation,
		'triangle-exclamation': faTriangleExclamation,
		copy: faCopy,
		compress: faCompress,
		expand: faExpand,
		plus: faPlus,
		trash: faTrash,
		pen: faPen,
		'location-crosshairs': faLocationCrosshairs,
		'car-battery': faCarBattery,
		video: faVideo,
		'video-slash': faVideoSlash,
		'volume-high': faVolumeHigh,
		'shield-halved': faShieldHalved,
		handcuffs: faHandcuffs,
		'briefcase-medical': faBriefcaseMedical,
		'circle-user': faCircleUser,
		phone: faPhone,
		flag: faFlag,
		check: faCheck,
		'walkie-talkie': faWalkieTalkie,
		helicopter: faHelicopter,
		motorcycle: faMotorcycle,
		'circle-question': faCircleQuestion,
		thumbtack: faThumbtack,
		'location-dot': faLocationDot,
		stopwatch: faStopwatch,
		'link-slash': faLinkSlash,
		camera: faCamera,
		'chevron-up': faChevronUp,
		cog: faCog,
		share: faShare,
		'truck-medical': faTruckMedical,
		'truck-ramp-box': faTruckRampBox,
		'clipboard-list': faClipboardList,
		'hourglass-half': faHourglassHalf,
		fire: faFire,
	};

	let { name, size = '1em' }: { name: string; size?: string } = $props();

	const icon = $derived(ICONS[name] ?? faCircleExclamation);
	const path = $derived(icon.icon[4] as string);
	const viewBox = $derived(`0 0 ${icon.icon[0]} ${icon.icon[1]}`);
</script>

<svg {viewBox} width={size} height={size} fill="currentColor" aria-hidden="true">
	<path d={path} />
</svg>
